### PR TITLE
ENV keys are strings by default

### PR DESCRIPTION
**Pull request by cpjolicoeur**
No need to map over them again, is there?

### CODE REVIEW

**Comment by cpjolicoeur** [comment]
I see why you guys probably did the map, cuz your test file uses a hash for it.  In truth, the ENV read from the app is strings, so the tests should just mimc that with strings.  I can update the test file as well with the PR; I just edited it directly on GH, didn't pull it down and run it locally to see the test failure.

**Comment by joelhawksley** [comment]
Wouldn't it be safer to allow either in the config file?

**Comment by cpjolicoeur** [comment]
In the config file sure, but this is the `ENV` object, not the config file data.  The data set in the sever ENV is going to always be strings.  The code change was dealing with that `ENV` object keys, not the config file data.

**Comment by joelhawksley** [comment]
rebase? :heart:

**Comment by adsteel** [comment]
@cpjolicoeur Is it really ALWAYS going to be strings? Is there no situation where other data types are put into an ENV hash?

**Comment by cpjolicoeur** [comment]
Two things, first these are just the keys we are talking about, not the whole object (values also).  Second, yes they will be strings.  These are env variables from the command line and operating system.  Even doing something like

   FOO_KEY=true rake my:task

with make `ENV['FOO_KEY']` not equal the boolean `true` but the string `true`.

That is just how the ENV works.

For this commit though, we are only concerned with the keys since that is all we are referencing, and those will always be strings.

**Comment by adsteel** [comment]
@cpjolicoeur Good to know, thanks. You convinced me.

**Comment by joelhawksley** [comment]
Closing due to inactivity.

**Pull request closed without merging**
