### PR TITLE
Environment compares Keysets to enforce ENV keys

### PR DESCRIPTION
**Pull request by mfrost**
This started with extraction of the File operations. Really, we have two ways of building comparable `Set`s. This clarifies that and adds some specs around file operations.

### CODE REVIEW

**Comment by joelhawksley** [comment]
Ideally, we'd squash the rubocop changes with the original implementation commit(s).

**Comment by mfrost** [comment]
Will squash rubocop stuff down.

@adsteel which functionality in particular? This PR started with a desire to separate and spec out file loading behavior.

**Comment by adsteel** [comment]
@mfrost The loading behavior separation. If we don't have a need for it to be separated, I'm not sure it justifies the added complexity. I was wondering if we had a use case we were trying to address.

**Comment by mfrost** [comment]
@adsteel I think it was mostly so that I could inject a test file and spec out the failure case / message.

@joelhawksley rubocop doesn't seem to like the default messages built into the error classes. Should I rework those so the messages live in the raising locations?

**Comment by adsteel** [comment]
@mfrost I see. I'm not sure that justifies the added complexity for me. I think I'd rather see us find a way to mock the fixture in the tests.

**Comment by adsteel** [comment]
Jan 2016. Whoa.

**Pull request closed without merging**
