### PR TITLE
Allow for usage outside of Rails environment

### PR DESCRIPTION
**Pull request by mfrost**
There is still potential for refactoring and cleanup, but the basic principle is here: allow for loading envforcer outside of a Rails app.

I'd love to continue cleaning up the separation, but wanted some feedback on the idea before proceeding.

### CODE REVIEW

**Comment by joelhawksley** [comment]
:+1: looks good. I'd be happy to merge once you have it cleaned up and passing CI, along with any changes to the Readme that would be necessary.

**Comment by mfrost** [comment]
I've made a few more changes and added some tests. There is still some clean up that can be done around each environment. Would love to extract the file loading at some point, but that doesn't have to happen here.

There is also opportunity to release a second gem called `envforcer-rails` like `dotenv` does so that the `require:` directive is not needed.

Let me know what you think.

**Comment by adsteel** [comment]
@mfrost Could you rebase? We broke your branch last Friday when we eliminated the environment-specific part of the config file.

**Comment by mfrost** [comment]
Sure, wasn't sure if rebase was your preferred method. Let me have a look at the most recent from upstream here...

**EDIT** This seems like I can remove a bunch of the `RailsEnvironment` code too. Do you still want to support `Rails.root` and friends? Is the working directory sufficient?

**Comment by joelhawksley** [comment]
@mfrost I'm fine with just supporting the working directory. The less coupled we are to Rails, the better.

**Comment by mfrost** [comment]
The rebase hit a few bumps, but I think I got it right. At this point, it is coupled to rails via a simple railtie. :+1:

**Comment by joelhawksley** [comment]
:clap: Good work @mfrost, I like it. Merging. Also, shoot me your contact info: joel@mojotech.com.

**Pull request merged**
